### ISSUE TITLE
Calling potential SNVs using pileup... Error.

### ISSUE THREAD

**Issue by AsclepiusDoc** [pjedge/longshot#44]
Hello longshot,

I am attempting to use longshot on a 14 GB genome and have recently run into the following error:

```
longshot: sam.c:2316: resolve_cigar2: Assertion `s->k < c->n_cigar' failed.
/var/spool/slurmd/job133909/slurm_script: line 17: 226239 Aborted   
```      
I was wondering if I could get some advice on how to approach this problem?

Kind Regards,

Alex

**Comment by vibansal** [comment]
It seems like the error is related to the cigar operations in the input file. Older versions of htslib had a limit on the max. number of cigar operations. If you are using an older version of htslib, it would be worth updating it.

**Comment by ddrichel** [comment]
I have the same issue, the problem seems to be with the rust-htslib version that comes with longshot. 
The data is ultralong HG002 ONT reads aligned with minimap2. The problem is NOT with large CIGAR strings (>65535 operations), the error persists after corresponding reads are removed. 
In Cargo.toml :
rust-htslib = "0.26.1" 

The next release of rust-htslib is 0.27.0 and longshot does not compile with that version, since it broke backward compatibility.
However, the compiler complains in only two places:


error[E0308]: mismatched types
   --> src/extract_fragments.rs:277:16
    |
277 |               >= bam_record
    |  ________________^
278 | |                 .cigar()
279 | |                 .end_pos()
    | |__________________________^ expected `i32`, found `i64`
    |
help: you can convert an `i64` to `i32` and panic if the converted value wouldn't fit
    |
277 |             >= bam_record
278 |                 .cigar()
279 |                 .end_pos().try_into().unwrap()
    |

error[E0308]: mismatched types
   --> src/extract_fragments.rs:280:44
    |
280 |         || (var_interval.end_pos as i32) < bam_record.pos()
    |                                            ^^^^^^^^^^^^^^^^ expected `i32`, found `i64`
    |
help: you can convert an `i64` to `i32` and panic if the converted value wouldn't fit
    |
280 |         || (var_interval.end_pos as i32) < bam_record.pos().try_into().unwrap()
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

Just implementing the suggested changes and adding:

`use std::convert::TryInto;`

to the src/extract_fragments.rs

does the job! Works with htslib 0.29.0 for me as well.

**Comment by vibansal** [comment]
Thank you @ddrichel  for finding the source of this problem and the fix. The incompatibility is due to the use of 64 bit integers in the later versions of htslib. I have pushed a commit to master to handle this. Thanks again.
